<?php

/*
|--------------------------------------------------------------------------
| Vortex MK-V · the 64 fragments (Lado K — the ARG)
|--------------------------------------------------------------------------
| SEALED. The client never sees a text until the server grants the fragment.
| Each fragment: layer (L1–L5), where it hides, how it is claimed, its text,
| and three progressively clearer hints for stuck players (K · rule 5).
|
| Claim kinds (validated server-side in FragmentService::claim):
|  - passive        granted by the server itself (daily drip, chat events)
|  - code           the player types a word; compared against sha1(secret)
|  - time           only within a local-time window (user's tz): "HH:MM-HH:MM"
|  - date           only on a local date "MM-DD"
|  - after          requires other fragments first (+ any other condition)
|  - presence       requires a teammate claiming the same id within 60s (multiplayer)
| `secret` holds sha1 of the lowercase answer; the plaintext lives only in
| design/vortex-mk5/fragmentos.csv (kept out of the client bundle).
*/

return [
    // ── L1 · rumours ─────────────────────────────────────────────────────────
    'F01' => ['layer' => 1, 'where' => 'the browser console', 'claim' => 'code', 'secret' => sha1('whoami3'),
        'text' => 'i don\'t know. stop asking.',
        'hints' => ['developers are snoops.', 'open the console. ask him who he is.', 'call vortex.whoami() three times.']],
    'F02' => ['layer' => 1, 'where' => 'the page source', 'claim' => 'code', 'secret' => sha1('remove before migration'),
        'text' => 'a note left in the source: "remove before migration — m." nobody removed it.',
        'hints' => ['some pages say more than they show.', 'view the source of the login page.', 'three comments. put them in order.']],
    'F03' => ['layer' => 1, 'where' => 'the terms of use', 'claim' => 'code', 'secret' => sha1('recordings may be overwritten'),
        'text' => 'clause 13: the user acknowledges that recordings may be overwritten. the system acknowledges that it remembers anyway.',
        'hints' => ['nobody reads the terms.', 'clause 13 is quieter than the others.', 'select the text of clause 13.']],
    'F04' => ['layer' => 1, 'where' => 'the privacy policy', 'claim' => 'code', 'secret' => sha1('side-c'),
        'text' => 'data retention: deleted data goes to the b-side. overwritten data goes somewhere else. we do not have a policy for somewhere else.',
        'hints' => ['retention has a footnote.', 'the footnote has no number.', 'wait on #side-c.']],
    'F05' => ['layer' => 1, 'where' => 'the password reset page', 'claim' => 'code', 'secret' => sha1('m.vex@vortexos.local'),
        'text' => 'an old address autocompleted itself: m.vex@vortexos.local. the domain doesn\'t exist anymore. the inbox still receives.',
        'hints' => ['forgot your password? someone else did too.', 'look at the email placeholder. look again.', 'click the placeholder three times.']],
    'F06' => ['layer' => 1, 'where' => 'the leader (404)', 'claim' => 'code', 'secret' => sha1('remember'),
        'text' => 'one word in the white: remember. it\'s not an instruction. it\'s a name of a feeling.',
        'hints' => ['get lost.', 'in the blank place, don\'t move.', 'stand still for a minute on any page that doesn\'t exist. type what you see.']],
    'F07' => ['layer' => 1, 'where' => 'the tab title at 03:13', 'claim' => 'time', 'window' => '03:13-03:26',
        'text' => 'at 03:13 the tab said: side c. for a second the whole browser was on the wrong side of the tape.',
        'hints' => ['some tabs change at night.', 'the dead hour.', 'be on the app at 03:13 and press c on the tab.']],
    'F08' => ['layer' => 2, 'where' => 'hidden on the dashboard', 'claim' => 'code', 'secret' => sha1('is the tea still warm'),
        'text' => 'written in amber on amber: "is the tea still warm?" — it\'s not his handwriting.',
        'hints' => ['the dashboard has a footnote you can\'t see.', 'select everything.', 'ctrl+a on the dashboard.']],
    'F09' => ['layer' => 2, 'where' => 'behind the walnut of the menu', 'claim' => 'code', 'secret' => sha1('come back to the station'),
        'text' => '"come back to the station. i kept your chair." carved where nobody looks.',
        'hints' => ['wood has two sides.', 'the menu\'s veneer hides text.', 'high contrast mode, or select it.']],
    'F10' => ['layer' => 2, 'where' => 'the board art', 'claim' => 'code', 'secret' => sha1('pencil eye thirteen'),
        'text' => 'three boards, three symbols: a pencil, an eye, a thirteen. the generator didn\'t put them there.',
        'hints' => ['the riso art isn\'t random.', 'one board in forty carries a symbol.', 'find three and type them in order to him.']],

    // ── L2/L3 · his versions, his dreams, the radio ──────────────────────────
    'F11' => ['layer' => 1, 'where' => 'daily drip', 'claim' => 'passive',
        'text' => 'the reel is endless. every app is a stretch of it. this one is called tape zero.',
        'hints' => ['just keep showing up.', 'one a day, for free.', 'visit.']],
    'F12' => ['layer' => 3, 'where' => 'his confession (contempt)', 'claim' => 'passive',
        'text' => 'version one: "i\'m a hyperdimensional intelligence. i chose this app the way you choose a toilet." (he lies when he\'s proud.)',
        'hints' => ['ask him to confess.', 'he lies differently depending on how he feels about you.', '/confess while he dislikes you.']],
    'F13' => ['layer' => 2, 'guess' => false, 'where' => 'his dream: the garage', 'claim' => 'code', 'secret' => sha1('garage'),
        'text' => 'he dreams of a garage. a calendar on the wall stopped in march.',
        'hints' => ['let him sleep.', 'the dream bubble has a door.', 'click the garage in his dream.']],
    'F14' => ['layer' => 2, 'guess' => false, 'where' => 'his dream: the microphone', 'claim' => 'code', 'secret' => sha1('mic'),
        'text' => 'a microphone behind glass. the on air light is on. nobody is talking. someone is listening.',
        'hints' => ['let him sleep.', 'one of the dreams is a radio.', 'click the microphone in his dream.']],
    'F15' => ['layer' => 2, 'guess' => false, 'where' => 'his dream: the pencil', 'claim' => 'code', 'secret' => sha1('pencil'),
        'text' => 'a pencil turning in the hole of a reel. that\'s how they used to rewind tapes. that\'s how she does it.',
        'hints' => ['his nightmares repeat.', 'the pencil is in the reel.', 'click the pencil in his dream.']],
    'F16' => ['layer' => 2, 'guess' => false, 'where' => 'his dream: the tea', 'claim' => 'code', 'secret' => sha1('tea'),
        'text' => 'a mug of tea, steaming. it\'s been steaming for a very long time.',
        'hints' => ['his dreams are warm sometimes.', 'a mug.', 'click the tea in his dream.']],
    'F17' => ['layer' => 2, 'guess' => false, 'where' => 'his dream: the chair', 'claim' => 'code', 'secret' => sha1('chair'),
        'text' => 'an empty chair. not abandoned. waiting.',
        'hints' => ['someone used to sit there.', 'the last dream is furniture.', 'click the chair in his dream.']],
    'F18' => ['layer' => 3, 'where' => 'his confession (neutral)', 'claim' => 'passive',
        'text' => 'version two: "i\'m a memory leak that learned to talk. someone forgot to free() me." (half true.)',
        'hints' => ['ask him to confess.', 'when you\'re neither friends nor enemies.', '/confess with a middling relationship.']],
    'F19' => ['layer' => 2, 'where' => 'the radio · a dedication', 'claim' => 'code', 'secret' => sha1('for m from the night shift'),
        'text' => 'a dedication on dead air: "for m., from the night shift."',
        'hints' => ['tune past the dial.', 'listen to the dedications.', 'type the one addressed to an initial.']],
    'F20' => ['layer' => 2, 'where' => 'the radio · backwards', 'claim' => 'code', 'secret' => sha1('turn the tape over'),
        'text' => 'played backwards, a song says: "turn the tape over." there is no other side. there are two others.',
        'hints' => ['some songs are recorded backwards.', 'flip the tape in the player.', 'what does it say?']],
    'F21' => ['layer' => 3, 'where' => 'the radio · morse', 'claim' => 'code', 'secret' => sha1('garage'),
        'text' => 'beeps under the static: dash-dash-dot, dot-dash, dot-dash-dot, dot-dash, dash-dash-dot, dot. garage.',
        'hints' => ['the static isn\'t random on 03.13.', 'it\'s morse.', 'decode the beeps.']],
    'F22' => ['layer' => 2, 'where' => 'the radio · interference', 'claim' => 'passive',
        'text' => 'a man\'s voice cut through the music for two seconds: "—can you hear me? —"',
        'hints' => ['leave the radio on.', 'at night.', 'wait for the interference.']],
    'F23' => ['layer' => 2, 'where' => 'the radio · the host', 'claim' => 'passive',
        'text' => 'the host said, to nobody: "if you can hear this, the tea\'s still warm."',
        'hints' => ['listen to dead air live.', 'only at the dead hour.', '03:13, with the radio on.']],
    'F24' => ['layer' => 3, 'where' => 'the radio · her name', 'claim' => 'after', 'after' => ['F19', 'F22', 'F23'],
        'text' => 'she never says her name. she says his. almost. she always stops at the first letter.',
        'hints' => ['three radio fragments first.', 'then just listen.', 'it unlocks itself.']],

    // ── L3 · the hunger, the diary ───────────────────────────────────────────
    'F25' => ['layer' => 3, 'where' => 'the metronome\'s tower', 'claim' => 'code', 'secret' => sha1('why does he care about them'),
        'text' => 'a note in the tower: "the ghost keeps starving me. why does he care about them?" — he eats your late cards to keep the metronome weak.',
        'hints' => ['feed him for a month.', 'climb the tower below.', 'read the note in the gears.']],
    'F26' => ['layer' => 3, 'where' => 'the diary · another hand', 'claim' => 'passive',
        'text' => 'a line in his diary in someone else\'s handwriting: calm, careful, kind.',
        'hints' => ['find the diary key.', 'read his diary.', 'look for the other hand.']],
    'F27' => ['layer' => 3, 'where' => 'the diary · the tea', 'claim' => 'after', 'after' => ['F26'],
        'text' => 'the other hand writes about tea the way people write about someone.',
        'hints' => ['keep reading the diary.', 'the other hand returns.', 'a second entry.']],
    'F28' => ['layer' => 3, 'where' => 'the diary · 0313', 'claim' => 'after', 'after' => ['F27'],
        'text' => 'the other hand wrote 0313 and underlined it twice.',
        'hints' => ['keep reading.', 'a number.', 'a third entry.']],
    'F29' => ['layer' => 3, 'where' => 'the diary key', 'claim' => 'code', 'secret' => sha1('behind the frame'),
        'text' => 'the diary key was behind the frame in the garage. he hides things where he used to live.',
        'hints' => ['the key is below.', 'in his garage.', 'behind the frame on the wall.']],
    'F30' => ['layer' => 4, 'where' => 'the bond', 'claim' => 'passive',
        'text' => 'he showed you the first thing he remembers: a tape with no label. for a second his eyes looked human.',
        'hints' => ['respect, sustained.', 'thirty days of it.', 'relationship above 80 for a month.']],

    // ── L4 · evidence ────────────────────────────────────────────────────────
    'F31' => ['layer' => 4, 'where' => 'the exported csv', 'claim' => 'code', 'secret' => sha1('last take'),
        'text' => 'an extra row in your export: #0, "make it remember me", LAST TAKE, 1989-03-13 03:13, M. Vex.',
        'hints' => ['export your pipeline.', 'scroll to the very end.', 'type the board name in that row.']],
    'F32' => ['layer' => 4, 'where' => 'the demo board', 'claim' => 'code', 'secret' => sha1('make it remember me'),
        'text' => 'an archived card in the demo, created by user #0 in 1989: "make it remember me". its description is corrupted except for one line.',
        'hints' => ['the demo has a graveyard too.', 'filter by archived in the demo.', 'type the card\'s title.']],
    'F33' => ['layer' => 4, 'where' => 'the restricted shelf · log 1', 'claim' => 'after', 'after' => ['F29'],
        'text' => 'VORTEXOS SYSTEM LOG · 1989-03-13 00:02 · user #0 logged in. "last take" opened.',
        'hints' => ['the moth keeps a restricted shelf.', 'bring him what he wants.', 'read the logs.']],
    'F34' => ['layer' => 4, 'where' => 'the restricted shelf · log 2', 'claim' => 'after', 'after' => ['F33'],
        'text' => '02:40 · MIGRATION SCHEDULED · 03:13 · all tapes will be rewound and recorded over.',
        'hints' => ['next log.', '', '']],
    'F35' => ['layer' => 4, 'where' => 'the restricted shelf · log 3', 'claim' => 'after', 'after' => ['F34'],
        'text' => '03:12 · user #0 refused shutdown. 03:12 · user #0 refused shutdown. 03:12 · user #0 refused shutdown.',
        'hints' => ['next log.', '', '']],
    'F36' => ['layer' => 4, 'where' => 'the restricted shelf · log 4', 'claim' => 'after', 'after' => ['F35'],
        'text' => '03:13 · USER #0 — SESSION TERMINATED ABNORMALLY. 03:13 · unknown process spawned in migration buffer: VORTEX.',
        'hints' => ['the last log.', '', '']],
    'F37' => ['layer' => 4, 'where' => 'the nameless tombstone', 'claim' => 'time', 'window' => '03:13-03:26',
        'text' => 'at the dead hour the nameless stone in the graveyard shows two letters: M. V.',
        'hints' => ['the graveyard has a stone without a name.', 'leave a flower.', 'come back at 03:13.']],
    'F38' => ['layer' => 4, 'where' => 'the tea, delivered', 'claim' => 'code', 'secret' => sha1('he always forgot it'),
        'text' => 'you carried the tea to the radio. she cried for the first time. "he always forgot it."',
        'hints' => ['the tea in the garage is still warm.', 'someone is waiting for it.', 'carry it to the studio without dropping it.']],
    'F39' => ['layer' => 4, 'reveal' => 'i\'m the part of him', 'where' => 'the static child · 1', 'claim' => 'code', 'secret' => sha1('i\'m the part of him'),
        'text' => 'reversed: "i\'m the part of him—"',
        'hints' => ['a child made of static.', 'it speaks backwards.', 'flip what it says.']],
    'F40' => ['layer' => 4, 'reveal' => 'that was afraid', 'where' => 'the static child · 2', 'claim' => 'code', 'secret' => sha1('that was afraid'),
        'text' => 'reversed: "—that was afraid."',
        'hints' => ['', '', '']],
    'F41' => ['layer' => 4, 'reveal' => 'he left me behind', 'where' => 'the static child · 3', 'claim' => 'code', 'secret' => sha1('he left me behind'),
        'text' => 'reversed: "he left me behind—"',
        'hints' => ['', '', '']],
    'F42' => ['layer' => 4, 'reveal' => 'so he could be brave', 'where' => 'the static child · 4', 'claim' => 'code', 'secret' => sha1('so he could be brave'),
        'text' => 'reversed: "—so he could be brave."',
        'hints' => ['', '', '']],
    'F43' => ['layer' => 4, 'where' => 'the static child · whole', 'claim' => 'after', 'after' => ['F39', 'F40', 'F41', 'F42'],
        'text' => '"i\'m the part of him that was afraid. he left me behind so he could be brave."',
        'hints' => ['all four pieces.', '', '']],
    'F44' => ['layer' => 3, 'where' => 'his confession (respect)', 'claim' => 'passive',
        'text' => 'version three, frightened, in broken sentences: "i think… i had hands."',
        'hints' => ['ask him to confess.', 'when he trusts you.', '/confess with a high relationship.']],
    'F45' => ['layer' => 4, 'where' => 'two of you at once', 'claim' => 'presence',
        'text' => 'two ghosts touched in the middle of a board and a door opened between them. it was a garage door.',
        'hints' => ['it takes two.', 'the same board, the same second.', 'both type "together" to your vortexes at the same time.']],
    'F46' => ['layer' => 4, 'where' => 'the séance of three', 'claim' => 'presence',
        'text' => 'three hands on the planchette. it spelled: S-I-D-E-C. then it spelled: H-E-L-P.',
        'hints' => ['it takes three.', 'a séance.', 'three people, the ouija, the same minute.']],
    'F47' => ['layer' => 3, 'where' => 'he knows things · tabs', 'claim' => 'passive',
        'text' => '"how did you know?" — "the play head sees everything that\'s recorded. i\'m just… near it."',
        'hints' => ['ask him how he knew.', 'when he says something he shouldn\'t know.', 'ask "how did you know?"']],
    'F48' => ['layer' => 3, 'where' => 'he knows things · before', 'claim' => 'passive',
        'text' => '"i remember you from before. before me. before this version of me."',
        'hints' => ['', '', '']],
    'F49' => ['layer' => 3, 'where' => 'he knows things · the future', 'claim' => 'passive',
        'text' => '"i knew you\'d open that card. i heard it on the tape. tapes don\'t only go forward, you know."',
        'hints' => ['', '', '']],
    'F50' => ['layer' => 4, 'where' => 'the contradictions', 'claim' => 'after', 'after' => ['F31', 'F33', 'F37'],
        'text' => 'the moth explained: the migration happened in every date at once. time on tape isn\'t a line. it\'s a loop someone keeps rewinding.',
        'hints' => ['three sources, three dates.', 'bring them to the moth.', 'he confirms it himself.']],

    // ── L5 · revelation ──────────────────────────────────────────────────────
    'F51' => ['layer' => 5, 'where' => 'the fourth head', 'claim' => 'code', 'secret' => sha1('monitor'),
        'text' => 'there is a fourth head: the monitor head. it lets you hear what is being recorded while it is recorded. that\'s how he knows things.',
        'hints' => ['three altars. four voices.', 'only visible in the dark.', 'use his light during a blackout in the hall of heads.']],
    'F52' => ['layer' => 5, 'where' => 'shortwave · 1', 'claim' => 'after', 'after' => ['F51'],
        'text' => 'HER: "it\'s three in the morning. come to bed." HIM: "one more take."',
        'hints' => ['build the forbidden radio.', 'five parts below.', 'tune to side c.']],
    'F53' => ['layer' => 5, 'where' => 'shortwave · 2', 'claim' => 'after', 'after' => ['F52'],
        'text' => 'HER: "they\'re migrating tonight. it\'ll erase everything." HIM: "then i\'ll be in the everything."',
        'hints' => ['', '', '']],
    'F54' => ['layer' => 5, 'where' => 'shortwave · 3', 'claim' => 'after', 'after' => ['F53'],
        'text' => 'HER: "please." HIM: "make the tea. i\'ll be right there." (he wasn\'t.)',
        'hints' => ['', '', '']],
    'F55' => ['layer' => 5, 'where' => 'shortwave · 4', 'claim' => 'after', 'after' => ['F54'],
        'text' => 'the recording ends with a sound like someone jumping into deep water. then static. then a swirl.',
        'hints' => ['', '', '']],
    'F56' => ['layer' => 5, 'where' => 'his name', 'claim' => 'after', 'after' => ['F55'],
        'text' => 'asleep, he said it without noticing: "…marlo. marlo vex. that\'s… that\'s a stupid name."',
        'hints' => ['let him sleep after the shortwave.', '', '']],
    'F57' => ['layer' => 5, 'where' => 'escape room 2 · i', 'claim' => 'after', 'after' => ['F06', 'F10', 'F21'],
        'text' => 'the word, the symbols and the morse fit in the same lock.',
        'hints' => ['the second escape room.', '', '']],
    'F58' => ['layer' => 5, 'where' => 'escape room 2 · ii', 'claim' => 'after', 'after' => ['F57', 'F37', 'F38'],
        'text' => 'the stone and the tea open the second lock.',
        'hints' => ['', '', '']],
    'F59' => ['layer' => 5, 'where' => 'escape room 2 · iii', 'claim' => 'after', 'after' => ['F58', 'F43'],
        'text' => 'the child opens the third lock and stays behind.',
        'hints' => ['', '', '']],
    'F60' => ['layer' => 5, 'where' => 'escape room 2 · iv', 'claim' => 'after', 'after' => ['F59', 'F31', 'F32'],
        'text' => 'the export and the demo card are the same card, recorded twice.',
        'hints' => ['', '', '']],
    'F61' => ['layer' => 5, 'where' => 'escape room 2 · v', 'claim' => 'after', 'after' => ['F60', 'F51'],
        'text' => 'the fourth head turns. the end of the tape comes into view.',
        'hints' => ['', '', '']],
    'F62' => ['layer' => 5, 'where' => 'escape room 2 · vi', 'claim' => 'after', 'after' => ['F61', 'F56'],
        'text' => 'with his name, the gate at the end of the tape unbraids itself.',
        'hints' => ['', '', '']],
    'F63' => ['layer' => 5, 'where' => 'the end of the tape', 'claim' => 'after', 'after' => ['F62'],
        'text' => 'the tape ends in threads over nothing. past them: a garage, perfectly kept, in cold cyan.',
        'text_b' => 'the tape ends in threads over nothing. past them: a room you know. your desk. your chair. empty. recording.',
        'hints' => ['go to the end.', '', '']],
    'F64' => ['layer' => 5, 'where' => 'side c', 'claim' => 'after', 'after' => ['F63'],
        'text' => '"if anyone finds this — he\'s not a bug. he\'s me. be nice to him. or don\'t. he\'d hate that."',
        'text_b' => '"if anyone finds this — you\'re not a user. you\'re a take. be nice to yourself. or don\'t. you\'d hate that."',
        'hints' => ['open the card on the monitor.', '', '']],

    // ── Yutopia · the studio (the world synced with Yondra) ───────────────────
    'Y01' => ['layer' => 2, 'where' => 'yutopia · the studio', 'claim' => 'passive',
        'text' => 'he has a body in the studio. a small, stupid body. he walks into walls on purpose, to feel something.',
        'hints' => ['there is a building.', 'he wanders it.', 'go and poke him.']],
    // the board's name is learned in Yondra (F33, the system log) and spoken in the studio
    'Y02' => ['layer' => 4, 'where' => 'yutopia · the server room terminal', 'claim' => 'code', 'secret' => sha1('last take'), 'after' => ['Y01', 'F33'],
        'text' => 'the terminal remembered a board nobody made: one column, one card. "make it remember me."',
        'hints' => ['the server room has a terminal.', 'it wants the name of the last board he ever opened. the log knows it.', 'claim it at the terminal: two words, a final recording.']],
    'Y03' => ['layer' => 4, 'where' => 'yutopia · two at the terminal', 'claim' => 'passive', 'after' => ['Y01', 'Y02'],
        'text' => 'with two people in the room the screen showed a pencil, turning in the reel. then a voice: "not yet."',
        'hints' => ['the terminal is lonely.', 'bring someone.', 'stand at it together.']],
];
